modLoader = "javafml"
loaderVersion = "[1,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL = "https://github.com/The-Aether-Team/Emissivity/issues"

[[mods]]
modId = "aether_emissivity"
version = "${file.jarVersion}"
displayName = "Emissivity"
updateJSONURL = "https://github.com/The-Aether-Team/Emissivity/raw/1.20.4-develop/update.json"
displayURL = "https://modrinth.com/mod/aether-emissivity"
logoFile = "emissivity_icon.png"
credits = "The Aether Team"
authors = "bconlon"
description = '''Adds various emissive textures for the Aether's content.'''

[[dependencies.aether_emissivity]]
    modId="neoforge"
    type = "required"
    versionRange="[20.4.167,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_emissivity]]
    modId = "aether"
    type = "required"
    versionRange = "[1.20.4-1.4.0-neoforge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_emissivity]]
    modId = "minecraft"
    type = "required"
    versionRange="[1.20.4]"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config="aether_emissivity.mixins.json"
