modLoader = "javafml"
loaderVersion = "[47,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL = "https://github.com/The-Aether-Team/Emissivity/issues"

[[mods]]
modId = "aether_emissivity"
version = "${file.jarVersion}"
displayName = "Emissivity"
updateJSONURL = "https://github.com/The-Aether-Team/Emissivity/raw/1.20.1-develop/update.json"
displayURL = "https://modrinth.com/mod/aether-emissivity"
logoFile = "emissivity_icon.png"
credits = "The Aether Team"
authors = "bconlon"
description = '''Adds various emissive textures for the Aether's content.'''

[[dependencies.aether_emissivity]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_emissivity]]
    modId = "aether"
    mandatory = true
    versionRange = "[1.20.1-1.0.0-beta.1.2-neoforge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_emissivity]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1]"
    ordering = "NONE"
    side = "BOTH"
